global:
  scrape_interval:     15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - prometheus:9090
  - job_name: gameshop
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
        - gameshop:8081