version: "3.8"

services:

  gameshop:
    build: .
    ports:
      - 8081:8080
    environment:
      - DB_URL
      - DB_USER
      - DB_PASS
    container_name: gameshop-container
    depends_on:
      - postgres
    volumes:
      - ./logs/application.log:/logs/application.log

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD= Dbeaver2022
    container_name: postgres-container
    volumes:
      - db-data:/var/lib/postgresql/data

  promtail:
    image: grafana/promtail:latest
    container_name: promtail_container
    volumes:
      - ./loki-stack/promtail/promtail-docker-config.yml:/etc/promtail/docker-config.yaml
      - ./logs/application.log:/var/log/application.log
    command: "--config.file=/etc/promtail/docker-config.yaml"

  loki:
    image: grafana/loki:latest
    container_name: loki_container
    ports:
      - 3100:3100

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./loki-stack/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    container_name: logging-prometheus

volumes:

  grafana-data:
    driver: local

  prometheus-data:
    driver: local

  db-data:
    driver: local